# Generated by Django 2.2.18 on 2021-03-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0004_auto_20210330_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
