# Generated by Django 2.2.18 on 2021-03-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0006_auto_20210330_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='vendor_location',
        ),
    ]
