# Generated by Django 2.2.18 on 2021-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0007_auto_20210330_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_shop_description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_shop_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_shop_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
