# Generated by Django 2.2.18 on 2021-03-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0008_auto_20210330_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vendor_shop_description',
            new_name='vendor_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vendor_shop_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vendor_shop_name',
        ),
    ]
