# Generated by Django 2.2.18 on 2021-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0009_auto_20210330_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
