# Generated by Django 2.2.18 on 2021-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0010_auto_20210330_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currentlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentlocation', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
