# Generated by Django 2.2.18 on 2021-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0011_currentlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlocation',
            name='currentlocation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
