# Generated by Django 2.2.18 on 2021-03-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0013_auto_20210330_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='latitude',
            new_name='vendor_latitude',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='longitude',
            new_name='vendor_longitude',
        ),
    ]
