# Generated by Django 2.2.18 on 2021-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0014_auto_20210330_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vendor_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
