# Generated by Django 2.2.18 on 2021-03-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0015_auto_20210330_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentlocation',
            old_name='currentlocation',
            new_name='location',
        ),
    ]
