# Generated by Django 2.2.18 on 2021-04-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0016_auto_20210331_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentlocation',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vendor_location',
            new_name='address',
        ),
    ]
