# Generated by Django 2.2.18 on 2021-04-01 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffenapp', '0017_auto_20210401_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg'), ('vegan', 'vegan')], default=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Cusine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cusinename', models.CharField(db_index=True, default='', max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cusine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiffenapp.Cusine'),
        ),
    ]
